spring:
  application:
    name: JRUFinalProject5
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
