spring:
  application:
    name: JRUFinalProject5
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
#  level.org.springframework: DEBUG
  level.org.springframework.web: DEBUG
jwt:
  secret: ${JWT_SECRET}