databaseChangeLog:
  - changeSet:
      id: add-fk-constraint-to-tasks
      author: ikazakov
      changes:
        - addForeignKeyConstraint:
            baseTableName: tasks
            baseColumnNames: user_id
            referencedTableName: users
            referencedColumnNames: id
            constraintName: fk_task_user